<?php

namespace Database\Seeders;

use App\Models\LearningRelatedTechnique;
use App\Models\LearningSuboutcome;
use App\Models\LearningSuboutcomeTechnique;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LearningSuboutcomeTechniqueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //LearningSuboutcomeTechnique::factory()->count(3)->create();
        // Array waarin de koppeling tussen suboutcomes en technieken wordt opgeslagen
        $suboutcomeTechniques = [
            'PROG0101' => ['Variabelen en datatypes'],
            'PROG0102' => ['Expressies en operatoren'],
            'PROG0103' => ['Controlestructuren'],
            'PROG0104' => ['Functies of methoden'],
            'PROG0105' => ['Datastructuren'],
            'PROG0106' => ['Algoritmen'],
            'PROG0107' => ['Datastructuren'],
            'PROG0108' => ['Objectgeorienteerde concepten'],
            'PROG0109' => ['Patroonherkenning'],
            'PROG0110' => ['Code-optimalisatie (DRY)'],
            'PROG0201' => ['Package Managers'],
            'PROG0202' => ['Softwareontwikkelingsprogramma’s en -tools'],
            'PROG0203' => ['Tool Selectie'],
            'PROG0204' => ['Pseudocode'],
            'PROG0205' => ['Criteria voor programmeertalen evaluatie'],
            'PROG0206' => ['Bibliothekenonderzoek'],
            'PROG0207' => ['Integratie van bibliotheken'],
            'PROG0301' => ['Object-Oriented Programming (OOP)'],
            'PROG0302' => ['Entity-Component-System (ECS)'],
            'PROG0303' => ['Functioneel programmeren'],
            'PROG0304' => ['Encapsulatie toepassen'],
            'PROG0305' => ['Modulariteit toepassen'],
            'PROG0306' => ['Inheritance toepassen'],
            'PROG0307' => ['Polymorphism toepassen'],
            'PROG0308' => ['Refactoring van klassen'],
            'PROG0309' => ['Interface ontwerp'],
            'PROG0310' => ['Gebruik van abstractie'],
            'PROG0401' => ['Gegevensmigratie'],
            'PROG0402' => ['Datastructuurtransformatie'],
            'PROG0403' => ['Minimalisatie van gegevensverlies'],
            'PROG0501' => ['Bestandsformaten'],
            'PROG0502' => ['Licenties en auteursrechten'],
            'PROG0503' => ['Integratietechnieken'],
            'PROG0601' => ['Coding style guide'],
            'PROG0602' => ['Naamgevingconventies'],
            'PROG0603' => ['Indentering en witruimte'],
            'PROG0604' => ['Commentaar en documentatie'],
            'PROG0605' => ['Naamgeving en beschrijvingen'],
            'PROG0606' => ['Gebruik van inline comments'],
            'PROG0607' => ['Documentatie genereren'],
            'PROG0701' => ['Statische code analyse'],
            'PROG0702' => ['Code formatteren'],
            'PROG0703' => ['Debuggen en testen'],
            'PROG0704' => ['Testcode schrijven'],
            'PROG0705' => ['Refactoring en hertesten'],
            'PROG0801' => ['Toegankelijkheidsrichtlijnen'],
            'PROG0802' => ['Toegankelijke code'],
            'PROG0803' => ['Testen op toegankelijkheid'],
            'PROG0804' => ['Toegankelijkheid van technologieën'],
            'PROG0805' => ['Gebruikersbehoeften'],
            'PROG0806' => ['Beperkingen van technologieën'],
            'PROG0807' => ['Handmatige en automatische testen'],
            'PROG0808' => ['Verbeteringen implementeren'],
            'PROG0809' => ['Herhaaldelijke testen'],
            'PROG0901' => ['Beveiligingsrisico\'s'],
            'PROG0902' => ['Veilige codeerpraktijken'],
            'PROG0903' => ['Coding richtlijnen'],
            'PROG0904' => ['Dependency management'],
            'PROG1001' => ['Herkenning van patronen'],
            'PROG1002' => ['Toepassing van patronen'],
            'PROG1003' => ['Implementatiedetails'],
            'PROG1004' => ['Testen en debuggen'],
            'ITSK0101' => ['Mappenstructuur aanmaken en beheren'],
            'ITSK0102' => ['Mappenstructuur aanmaken en beheren'],
            'ITSK0103' => ['Mappenstructuur aanmaken en beheren'],
            'ITSK0104' => ['Mappenstructuur aanmaken en beheren'],
            'ITSK0105' => ['Bestanden comprimeren en uitpakken'],
            'ITSK0106' => ['Navigeren met MS-DOS/Terminal'],
            'ITSK0107' => ['Navigeren in Linux'],
            'ITSK0108' => ['Navigeren in Linux'],
            'ITSK0109' => ['Plaatsen van programma\'s en websites'],
            'ITSK0110' => ['Herkennen van bestandsformaten'],
            'ITSK0201' => ['Kennis van licenties'],
            'ITSK0202' => ['Uitleggen van licentiesoorten'],
            'ITSK0203' => ['Gebruik van LicenseFinder'],
            'ITSK0204' => ['Verplichtingen van open-source licenties'],
            'ITSK0205' => ['Licentievoorwaarden bij externe bibliotheken'],
            'ITSK0206' => ['Bedrijfsrichtlijnen voor licenties'],
            'ITSK0207' => ['Respecteren van auteursrechten'],
            'ITSK0301' => ['Algemene dreigingen en beveiliging'],
            'ITSK0302' => ['Algemene dreigingen en beveiliging'],
            'ITSK0303' => ['Herkennen van IP-adressen en kennis over poorten'],
            'ITSK0304' => ['Herkennen van IP-adressen en kennis over poorten'],
            'ITSK0305' => ['Beveiliging van systemen'],
            'ITSK0306' => ['Beveiliging van systemen'],
            'ITSK0307' => ['Beveiliging van systemen'],
            'ITSK0308' => ['Kennis van ICT-infrastructuur en devices'],
            'ITSK0309' => ['Kennis van ICT-infrastructuur en devices'],
            'ITSK0401' => ['Ontwikkelingen in ICT-infrastructuur'],
            'ITSK0402' => ['Consequenties van cloud services'],
            'ITSK0403' => ['Consequenties van cloud services'],
            'ITSK0404' => ['Docker en containerisatie'],
            'ITSK0405' => ['Docker en containerisatie'],
            'ITSK0406' => ['Docker en containerisatie'],
            'ITSK0501' => ['Copyright en auteursrecht'],
            'ITSK0502' => ['Privacy en toegankelijkheid'],
            'ITSK0503' => ['Computercriminaliteit'],
            'ITSK0504' => ['Toepassing van wetgeving en bedrijfsnormen'],
            'ITSK0505' => ['Toepassing van wetgeving en bedrijfsnormen'],
            'ITSK0506' => ['Toepassing van wetgeving en bedrijfsnormen'],
            'ITSK0601' => ['Security en privacy in ontwerp'],
            'ITSK0602' => ['Security en privacy in ontwerp'],
            'ITSK0603' => ['Security en privacy in ontwerp'],
            'ITSK0604' => ['Security en privacy in ontwerp'],
            'ITSK0605' => ['Security en privacy in ontwerp'],
            'ITSK0701' => ['Beheer van assets'],
            'ITSK0801' => ['Git-commando\'s'],
            'ITSK0802' => ['Git-autorisatie en merging'],
            'ITSK0803' => ['Git-branching'],
            'ITSK0804' => ['Continuous Integration en Continuous Deployment'],
            'ITSK0805' => ['Github Pages'],
            'COMM0101' => ['Sitemap, wireframe, DoD, userstories, acceptatiecriteria'],
            'COMM0102' => ['Daily, Trellobord'],
            'COMM0103' => ['LSD'],
            'COMM0104' => ['Escaleren'],
            'COMM0105' => ['LSD'],
            'COMM0106' => ['Overleggen'],
            'COMM0107' => ['LSD'],
            'COMM0108' => ['LSD'],
            'COMM0109' => ['LSD'],
            'COMM0110' => ['LSD'],
            'COMM0111' => ['LSD'],
            'COMM0201' => ['Analysevaardigheden'],
            'COMM0202' => ['Analysevaardigheden'],
            'COMM0301' => ['Retrospective'],
            'COMM0302' => ['Retrospective'],
            'COMM0303' => ['Retrospective'],
            'COMM0304' => ['Retrospective'],
            'COMM0401' => ['Retrospective'],
            'COMM0402' => ['Retrospective'],
            'COMM0403' => ['Retrospective'],
            'COMM0404' => ['Retrospective'],
            'COMM0501' => ['Reflectie'],
            'COMM0502' => ['Reflectie'],
            'COMM0503' => ['Reflectie'],
            'COMM0504' => ['Reflectie'],
            'COMM0505' => ['Reflectie'],
            'COMM0601' => ['Scrum, risicomanagement'],
            'COMM0701' => ['Motiverende aspecten'],
            'COMM0702' => ['Teamcohesie'],
            'COMM0703' => ['Feedback van team'],
            'COMM0704' => ['Werkdruk en werkplezier'],
            'COMM0705' => ['Lange termijn motivatie'],
            'COMM0801' => ['Kwaliteitscriteria, MoSCoW'],
            'COMM0802' => ['Inleiding, kern, afsluiting'],
            'COMM0803' => ['Codekwaliteit'],
            'COMM0804' => ['Integratie(testen)'],
            'COMM0805' => ['Evaluatie met belanghebbenden'],
            'COMM0901' => ['Feedback ontvangen'],
            'COMM0902' => ['Zelfrapportage'],
            'COMM0903' => ['Actieve informatievergaring'],
            'COMM0904' => ['Presentatievaardigheden'],
            'COMM0905' => ['Feedback vragen'],
            'COMM0906' => ['Actief luisteren'],
            'COMM0907' => ['Diplomatieke communicatie'],
            'COMM0908' => ['Informatie-uitwisseling'],
            'COMM1001' => ['Feedback geven'],
            'COMM1002' => ['Feedback ontvangen'],
            'COMM1003' => ['Doorvragen bij feedback'],
            'COMM1004' => ['Feedback toepassen'],
            'COMM1101' => ['Zelfstandig werken'],
            'COMM1102' => ['Verantwoordelijkheid nemen'],
            'COMM1201' => ['Daily standup'],
            'COMM1202' => ['Retrospective'],
            'COMM1203' => ['Daily standup'],
            'COMM1204' => ['Samenwerking'],
            'COMM1205' => ['Organisatienormen'],
            'COMM1206' => ['Afspraken nakomen'],
            'COMM1207' => ['Werkafspraken'],
            'COMM1208' => ['Overleg'],
            'COMM1209' => ['Ruimte geven'],
            'COMM1210' => ['Eenduidige afspraken'],
            'COMM1211' => ['Procedures volgen'],
            'COMM1301' => ['Iteratief ontwikkelen'],
            'COMM1302' => ['Incrementeel ontwikkelen'],
            'COMM1303' => ['Test-driven development (TDD)'],
            'COMM1304' => ['Agile'],
            'COMM1305' => ['Vergelijking methodieken'],
            'COMM1401' => ['Scrumboard'],
            'COMM1402' => ['Daily standup'],
            'COMM1403' => ['Daily standup'],
            'COMM1404' => ['Productbacklog, user stories'],
            'COMM1405' => ['Pokeren'],
            'COMM1406' => ['Sprintplanning'],
            'COMM1407' => ['Sprintplanning'],
            'COMM1408' => ['Burndown chart'],
            'COMM1501' => ['Sprintreview'],
            'COMM1502' => ['Presentatievaardigheden'],
            'COMM1503' => ['Presentatievaardigheden'],
            'COMM1504' => ['Communicatievaardigheden'],
            'COMM1505' => ['Verantwoordingsvaardigheden'],
            'COMM1506' => ['Argumentatievaardigheden'],
            'COMM1507' => ['Vragen stellen'],
            'COMM1508' => ['Communicatiestijl aanpassen'],
            'COMM1601' => ['Probleemoplossingstechnieken'],
            'COMM1602' => ['Luistervaardigheden'],
            'COMM1603' => ['Probleemidentificatie'],
            'COMM1604' => ['Advies vragen'],
            'COMM1605' => ['Samenwerkingstechnieken'],
            'COMM1606' => ['Zelfredzaamheid'],
            'COMM1701' => ['Retrospective'],
            'COMM1702' => ['Analysevaardigheden'],
            'COMM1703' => ['Retrospective'],
            'COMM1704' => ['Analysevaardigheden'],
            'ONTW0101' => ['Scrum bord, product backlog, user story'],
            'ONTW0102' => ['Scrumboard, Daily standup'],
            'ONTW0103' => ['Risico-inschatting, MoSCoW'],
            'ONTW0104' => ['Scrumboard, Daily standup'],
            'ONTW0105' => ['ERD\'s, klassediagrammen'],
            'ONTW0201' => ['Risico-inschatting'],
            'ONTW0202' => ['MoSCoW'],
            'ONTW0203' => ['Risico-inschatting'],
            'ONTW0204' => ['Scrumboard, Daily standup'],
            'ONTW0205' => ['Risicodocumentatie'],
            'ONTW0301' => ['Sitemap'],
            'ONTW0302' => ['Wireframe'],
            'ONTW0303' => ['Mockup'],
            'ONTW0304' => ['Prototyping'],
            'ONTW0305' => ['UX/UI principes'],
            'ONTW0306' => ['Toegankelijkheidsrichtlijnen'],
            'ONTW0401' => ['ERD'],
            'ONTW0402' => ['Class Diagram'],
            'ONTW0403' => ['Flowchart'],
            'ONTW0404' => ['Use Case Diagram'],
            'ONTW0405' => ['Activity Diagram'],
            'ONTW0501' => ['Privacy by Design'],
            'ONTW0502' => ['Toegankelijkheidsrichtlijnen'],
            'ONTW0503' => ['Ethische checklist'],
            'ONTW0504' => ['Security by Design'],
            'ONTW0601' => ['Testscenario\'s maken'],
            'ONTW0602' => ['Unit test, integratietest, acceptatietest'],
            'ONTW0603' => ['Testomgeving, testdata'],
            'ONTW0604' => ['Testrapport'],
            'ONTW0605' => ['User stories, acceptatietest'],
            'ONTW0606' => ['User stories, acceptatietest'],
            'ONTW0607' => ['Acceptatietest, testrapport, unit testing'],
        ];

        // Doorloop elke suboutcome en koppel de juiste technieken
        foreach ($suboutcomeTechniques as $suboutcomeNumber => $techniques) {
            // Haal de juiste suboutcome op
            $suboutcome = LearningSuboutcome::where('number', $suboutcomeNumber)->first();

            // Haal elke techniek op en maak de koppeling
            foreach ($techniques as $techniqueName) {
                $technique = LearningRelatedTechnique::where('name', $techniqueName)->first();

                // Voeg de koppeling toe aan de suboutcome_techniques tabel
                if ($suboutcome && $technique) {
                    LearningSuboutcomeTechnique::create([
                        'learning_suboutcome_id' => $suboutcome->id,
                        'learning_related_technique_id' => $technique->id,
                    ]);
                }
            }
        }
    }
}
