<?php

namespace Database\Seeders;

use App\Models\LearningRelatedTechnique;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LearningRelatedTechniqueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //LearningRelatedTechnique::factory()->count(10)->create();
        // Unieke technieken uit de Excel-lijst
        $techniques = [
            'Variabelen en datatypes',
            'Expressies en operatoren',
            'Controlestructuren',
            'Functies of methoden',
            'Datastructuren',
            'Algoritmen',
            'Objectgeorienteerde concepten',
            'Patroonherkenning',
            'Code-optimalisatie (DRY)',
            'Package Managers',
            'Softwareontwikkelingsprogramma’s en -tools',
            'Tool Selectie',
            'Pseudocode',
            'Criteria voor programmeertalen evaluatie',
            'Bibliothekenonderzoek',
            'Integratie van bibliotheken',
            'Object-Oriented Programming (OOP)',
            'Entity-Component-System (ECS)',
            'Functioneel programmeren',
            'Encapsulatie toepassen',
            'Modulariteit toepassen',
            'Inheritance toepassen',
            'Polymorphism toepassen',
            'Refactoring van klassen',
            'Interface ontwerp',
            'Gebruik van abstractie',
            'Gegevensmigratie',
            'Datastructuurtransformatie',
            'Minimalisatie van gegevensverlies',
            'Bestandsformaten',
            'Licenties en auteursrechten',
            'Integratietechnieken',
            'Coding style guide',
            'Naamgevingconventies',
            'Indentering en witruimte',
            'Commentaar en documentatie',
            'Naamgeving en beschrijvingen',
            'Gebruik van inline comments',
            'Documentatie genereren',
            'Statische code analyse',
            'Code formatteren',
            'Debuggen en testen',
            'Testcode schrijven',
            'Refactoring en hertesten',
            'Toegankelijkheidsrichtlijnen',
            'Toegankelijke code',
            'Testen op toegankelijkheid',
            'Toegankelijkheid van technologieën',
            'Gebruikersbehoeften',
            'Beperkingen van technologieën',
            'Handmatige en automatische testen',
            'Verbeteringen implementeren',
            'Herhaaldelijke testen',
            'Beveiligingsrisico\'s',
            'Veilige codeerpraktijken',
            'Coding richtlijnen',
            'Dependency management',
            'Herkenning van patronen',
            'Toepassing van patronen',
            'Implementatiedetails',
            'Testen en debuggen',
            'Mappenstructuur aanmaken en beheren',
            'Bestanden comprimeren en uitpakken',
            'Navigeren met MS-DOS/Terminal',
            'Navigeren in Linux',
            'Plaatsen van programma\'s en websites',
            'Herkennen van bestandsformaten',
            'Kennis van licenties',
            'Uitleggen van licentiesoorten',
            'Gebruik van LicenseFinder',
            'Verplichtingen van open-source licenties',
            'Licentievoorwaarden bij externe bibliotheken',
            'Bedrijfsrichtlijnen voor licenties',
            'Respecteren van auteursrechten',
            'Algemene dreigingen en beveiliging',
            'Herkennen van IP-adressen en kennis over poorten',
            'Beveiliging van systemen',
            'Kennis van ICT-infrastructuur en devices',
            'Ontwikkelingen in ICT-infrastructuur',
            'Consequenties van cloud services',
            'Docker en containerisatie',
            'Copyright en auteursrecht',
            'Privacy en toegankelijkheid',
            'Computercriminaliteit',
            'Toepassing van wetgeving en bedrijfsnormen',
            'Security en privacy in ontwerp',
            'Beheer van assets',
            'Git-commando\'s',
            'Git-autorisatie en merging',
            'Git-branching',
            'Continuous Integration en Continuous Deployment',
            'Github Pages',
            'Sitemap, wireframe, DoD, userstories, acceptatiecriteria',
            'Daily, Trellobord',
            'LSD',
            'Escaleren',
            'Overleggen',
            'Analysevaardigheden',
            'Retrospective',
            'Scrum, risicomanagement',
            'Motiverende aspecten',
            'Teamcohesie',
            'Feedback van team',
            'Werkdruk en werkplezier',
            'Lange termijn motivatie',
            'Kwaliteitscriteria, MoSCoW',
            'Inleiding, kern, afsluiting',
            'Codekwaliteit',
            'Integratie(testen)',
            'Evaluatie met belanghebbenden',
            'Feedback ontvangen',
            'Zelfrapportage',
            'Actieve informatievergaring',
            'Presentatievaardigheden',
            'Feedback vragen',
            'Actief luisteren',
            'Diplomatieke communicatie',
            'Informatie-uitwisseling',
            'Feedback geven',
            'Feedback ontvangen',
            'Doorvragen bij feedback',
            'Feedback toepassen',
            'Zelfstandig werken',
            'Verantwoordelijkheid nemen',
            'Daily standup',
            'Samenwerking',
            'Organisatienormen',
            'Afspraken nakomen',
            'Werkafspraken',
            'Ruimte geven',
            'Eenduidige afspraken',
            'Procedures volgen',
            'Iteratief ontwikkelen',
            'Incrementeel ontwikkelen',
            'Test-driven development (TDD)',
            'Agile',
            'Vergelijking methodieken',
            'Scrumboard',
            'Pokeren',
            'Sprintplanning',
            'Burndown chart',
            'Sprintreview',
            'Communicatievaardigheden',
            'Verantwoordingsvaardigheden',
            'Argumentatievaardigheden',
            'Vragen stellen',
            'Communicatiestijl aanpassen',
            'Probleemoplossingstechnieken',
            'Luistervaardigheden',
            'Probleemidentificatie',
            'Advies vragen',
            'Samenwerkingstechnieken',
            'Zelfredzaamheid',
            'Analysevaardigheden',
            'Scrum bord, product backlog, user story',
            'Scrumboard, Daily standup',
            'Risico-inschatting, MoSCoW',
            'ERD\'s, klassediagrammen',
            'Risicodocumentatie',
            'Sitemap',
            'Wireframe',
            'Mockup',
            'Prototyping',
            'UX/UI principes',
            'Toegankelijkheidsrichtlijnen',
            'ERD',
            'Class Diagram',
            'Flowchart',
            'Use Case Diagram',
            'Activity Diagram',
            'Privacy by Design',
            'Ethische checklist',
            'Security by Design',
            'Testscenario\'s maken',
            'Unit test, integratietest, acceptatietest',
            'Testomgeving, testdata',
            'Testrapport',
            'User stories, acceptatietest',
            'Acceptatietest, testrapport, unit testing',
        ];

        // Voeg elke techniek toe aan de tabel
        foreach ($techniques as $technique) {
            LearningRelatedTechnique::create(['name' => $technique]);
        }
    }
}
